### ISSUE TITLE
Self-host docker

### ISSUE THREAD

**Issue by bokachodalawdsa** [stack-auth/stack#265] opened 2024-09-24 06:28 UTC
Getting errors after errors. Why is there no docker support?

**Comment by fomalhautb** [comment] 2024-09-24 17:37
The self-host doc is quite new and it reflects our own self-host process. We do understand that a docker compose file is easier for most people, we are going to create one soon

**Comment by jshimko** [comment] 2024-09-24 21:35
I currently have a fork with working Docker builds and a single-command docker-compose based build/startup process.  I've been using it for several weeks at this point to iron out issues and simplify the setup.  I also built a Helm chart for Kubernetes deployments that I'm already using with our deployed services.  

I'll be opening a PR here for the Docker stuff tomorrow and will write up docs for the Helm/Kubernetes deploys as soon as I'm done putting a few production quality example configs together (to make it easier for those that are less familiar with Kubernetes).  Assuming my Docker PR gets merged, the Docker Compose build/deployment process will be as simple as...

```sh
docker compose build
docker compose up -d
```

Kubernetes will definitely be a bit more involved than that, but I think everyone probably already knows that about Kubernetes.  ;)

**Comment by fomalhautb** [comment] 2024-09-24 23:36
> I currently have a fork with working Docker builds and a single-command docker-compose based build/startup process. I've been using it for several weeks at this point to iron out issues and simplify the setup. I also built a Helm chart for Kubernetes deployments that I'm already using with our deployed services.
> 
> I'll be opening a PR here for the Docker stuff tomorrow and will write up docs for the Helm/Kubernetes deploys as soon as I'm done putting a few production quality example configs together (to make it easier for those that are less familiar with Kubernetes). Assuming my Docker PR gets merged, the Docker Compose build/deployment process will be as simple as...
> 
> ```shell
> docker compose build
> docker compose up -d
> ```
> 
> Kubernetes will definitely be a bit more involved than that, but I think everyone probably already knows that about Kubernetes. ;)

That is awesome! I just got started with it but since you already have something working, I will just wait for your PR then!

**Comment by csyedbilal** [comment] 2024-09-30 09:40
root@stack-auth:~/stack/apps/dashboard# pnpm run dev

> @stackframe/stack-dashboard@2.6.0 dev /root/stack/apps/dashboard
> next dev --port 8101

  ▲ Next.js 14.2.3
  - Local:        http://localhost:8101
  - Environments: .env

 ✓ Starting...
   automatically enabled Fast Refresh for 1 custom loader
 ✓ Ready in 1398ms
 ○ Compiling /src/middleware ...
 ✓ Compiled /src/middleware in 665ms (331 modules)
 ○ Compiling / ...
 ✓ Compiled / in 7.7s (4063 modules)
 GET / 200 in 8174ms
 ✓ Compiled /projects in 461ms (2294 modules)
 ✓ Compiled in 798ms (1788 modules)
 GET /favicon.ico 200 in 1736ms
 GET /projects 200 in 965ms
 ⚠ Fast Refresh had to perform a full reload. Read more: https://nextjs.org/docs/messages/fast-refresh-reload
Error: aborted
    at abortIncoming (node:_http_server:797:17)
    at socketOnClose (node:_http_server:791:3)
    at Socket.emit (node:events:531:35)
    at Socket.emit (node:domain:488:12)
    at TCP.<anonymous> (node:net:339:12)
    at TCP.callbackTrampoline (node:internal/async_hooks:130:17) {
  code: 'ECONNRESET'
}
 ⨯ uncaughtException: Error: aborted
    at abortIncoming (node:_http_server:797:17)
    at socketOnClose (node:_http_server:791:3)
    at Socket.emit (node:events:531:35)
    at Socket.emit (node:domain:488:12)
    at TCP.<anonymous> (node:net:339:12)
    at TCP.callbackTrampoline (node:internal/async_hooks:130:17) {
  code: 'ECONNRESET'
}
 ⨯ uncaughtException: Error: aborted
    at abortIncoming (node:_http_server:797:17)
    at socketOnClose (node:_http_server:791:3)
    at Socket.emit (node:events:531:35)
    at Socket.emit (node:domain:488:12)
    at TCP.<anonymous> (node:net:339:12)
    at TCP.callbackTrampoline (node:internal/async_hooks:130:17) {
  code: 'ECONNRESET'
}
 ✓ Compiled /handler/[...stack] in 466ms (4103 modules)
 GET /handler/sign-in?after_auth_return_to=%2Fprojects 200 in 1125ms
 ⚠ Fast Refresh had to perform a full reload. Read more: https://nextjs.org/docs/messages/fast-refresh-reload

api: 
[dev] [API REQ] [f7qa1wbn6zrngdnd] GET http://localhost:8102/api/v1/users/me
[dev] [    ERR] [f7qa1wbn6zrngdnd] GET http://localhost:8102/api/v1/users/me: You have specified 'me' as a userId, but did not provide authentication for a user.
[dev]  GET /api/v1/users/me 200 in 15ms
![Screenshot_143](https://github.com/user-attachments/assets/ebd1c820-61b7-4354-9790-5d21caf8d5c9)

**Comment by jshimko** [comment] 2024-09-30 10:08
@csyedbilal You need to run that command from the root of the repo, not the dashboard directory. Follow the docs closely.  Every command is always from the root directory.

**Comment by csyedbilal** [comment] 2024-10-01 05:11
@jshimko please check dash: http://5.9.178.126:8101/
Api : http://5.9.178.126:8102/

it is just loading up again again.
i did manually i tried same issue 

and follow this but same
https://github.com/stack-auth/stack/pull/280

**Comment by csyedbilal** [comment] 2024-10-01 18:39
@jshimko  
I’ve been following the PR for Docker builds, and I’m experiencing issues with cookies when running the setup.

git clone --single-branch -b docker-builds https://github.com/jshimko/stack.git stack-docker
cd stack-docker
pnpm docker:up

I’ve set up an NGINX proxy with SSL on the following domains:

https://api.huctech.me/
https://apps.huctech.me/projects
same issue infinite loop of redirects in the browser.

![image](https://github.com/user-attachments/assets/e0d7c1d8-7861-4c3a-80b3-bbe1224a0f4b)

Steps Taken
I tried setting NEXT_PUBLIC_INSECURE_COOKIE=true in the environment variables to bypass the issue temporarily. However, this did not resolve the problem.

I followed the instructions regarding rebuilds, i.e., if code is changed, I explicitly ran:
pnpm docker:build
pnpm docker:up

Request
Could you please advise on any further steps or potential fixes? I’m not sure if I’m missing something, but the cookie issue is preventing progress despite the NEXT_PUBLIC_INSECURE_COOKIE variable being set.

Thanks in advance for your help!

**Comment by jshimko** [comment] 2024-10-01 21:49
@csyedbilal I assume it's a configuration issue because I have those same Docker builds deployed with no issues.  Make sure you have set all of your environment variables for URL's, API keys, etc.  Just leaving everything like it is on my branch is NOT adequate or secure.  You need to configure things for your own deployments.  You also don't do that by setting new values in the Dockerfile and building again (which it appears you did above).  You set them at runtime using whatever tool is running your containers.  If that's Docker Compose, you either set values in the compose config file or the .env.docker file it currently loads.

I feel like I should also mention that if you're not comfortable with configuring and debugging Docker builds in production, you may want to consider Stack's hosted service.  Especially because this is user authentication and security is very important in this context.  Just something to consider.

For example, since I can see that you have just used the default docker-compose config that is intended for local development and testing Docker builds, I now have enough information to access your database (and I just did).  I can also be reasonably sure you used default secret values as well, so that also means I have full access to your Stack API (also just confirmed by listing API keys in your database).

![image](https://github.com/user-attachments/assets/566f34d8-a30e-42ff-a024-6dd7bf2ef776)

So yeah, I would definitely make sure you know what you're doing before self hosting something like a user auth service.  Step 1 - don't expose the Postgres container port publicly EVER.  Step 2 - don't use usernames, passwords, secrets, etc. from a public open source repo.  Always configure everything yourself or else anyone with access to the repo will know your secrets.

**Comment by csyedbilal** [comment] 2024-10-02 16:13
@jshimko it is worked thanks!

but i did git pull to move production.

`stack-backend    | All migrations have been successfully applied.
stack-backend    | Running seed script...
stack-backend    | Seeding database...
stack-backend    | PrismaClientValidationError:
stack-backend    | Invalid prisma.project.create() invocation:
stack-backend    |
stack-backend    | {
stack-backend    |   data: {
stack-backend    |     id: "internal",
stack-backend    |     displayName: "Stack Dashboard",
stack-backend    |     description: "Stack's admin dashboard",
stack-backend    |     isProductionMode: false,
stack-backend    |     apiKeySets: {
stack-backend    |       create: [
stack-backend    |         {
stack-backend    |           description: "Internal API key set",
stack-backend    |           publishableClientKey: "this-publishable-client-key-                                                                                        is-for-local-development-only",
stack-backend    |           secretServerKey: "this-secret-server-key-is-for-loc                                                                                        al-development-only",
stack-backend    |           superSecretAdminKey: "this-super-secret-admin-key-i                                                                                        s-for-local-development-only",
stack-backend    |           expiresAt: new Date("2099-12-31T23:59:59.000Z")
stack-backend    |         }
stack-backend    |       ]
stack-backend    |     },
stack-backend    |     config: {
stack-backend    |       create: {
stack-backend    |         allowLocalhost: true,
stack-backend    |         signUpEnabled: true,
stack-backend    |         emailServiceConfig: {
stack-backend    |           create: {
stack-backend    |             proxiedEmailServiceConfig: {
stack-backend    |               create: {}
stack-backend    |             }
stack-backend    |           }
stack-backend    |         },
stack-backend    |         createTeamOnSignUp: false,
stack-backend    |         clientTeamCreationEnabled: false,
stack-backend    |         authMethodConfigs: {
stack-backend    |           create: [
stack-backend    |             {
stack-backend    |               otpConfig: {
stack-backend    |                 create: {
stack-backend    |                   contactChannelType: "EMAIL"
stack-backend    |                 }
stack-backend    |               }
stack-backend    |             },
stack-backend    |             {
stack-backend    |               passwordConfig: {
stack-backend    |                 create: {
stack-backend    |                   identifierType: "EMAIL"
stack-backend    |                 }
stack-backend    |               }
stack-backend    |             }
stack-backend    |           ]
stack-backend    |         }
stack-backend    |       }
stack-backend    |     }
stack-backend    |   }
stack-backend    | }
stack-backend    |
stack-backend    | Unknown argument identifierType. Available options are mark                                                                                        ed with ?.
stack-backend    |     at Dn (/app/apps/backend/seed-self-host.js:4468:13)
stack-backend    |     at Mn.handleRequestError (/app/apps/backend/seed-self-hos                                                                                        t.js:4991:11)
stack-backend    |     at Mn.handleAndLogRequestError (/app/apps/backend/seed-se                                                                                        lf-host.js:4982:16)
stack-backend    |     at Mn.request (/app/apps/backend/seed-self-host.js:4973:1                                                                                        6)
stack-backend    |     at async l (/app/apps/backend/seed-self-host.js:5366:21)
stack-backend    |     at async /app/apps/backend/seed-self-host.js:6053:28
stack-backend    |     at async Proxy._transactionWithCallback (/app/apps/backen                                                                                        d/seed-self-host.js:5341:17)
stack-backend    |     at async seed (/app/apps/backend/seed-self-host.js:6052:3                                                                                        ) {
stack-backend    |   clientVersion: '5.20.0'
stack-backend    | }
stack-backend exited with code 1`

thanks again for security recommendations!

**Closed** 2024-12-05 17:02 UTC
