### ISSUE TITLE
StackAssertionError: Failed to send request - INFINITE_LOOP_DETECTED

### ISSUE THREAD

**Issue by hrmoller** [stack-auth/stack#319] opened 2024-10-23 20:10 UTC
I'm seeing the below error quite a bit in the logs on Vercel but don't see it locally at all.

I have not tracked it down to what part of my own code that provokes this error to happen but will post here when/if I track it down. However, I have the following code in my `middleware.ts` and I suspect that to be the place that triggers the error below.

I'm not making any direct calls to `/api/v1/users/me` but I call `await stackServerApp.getUser()` a lot of places in my application.

**Versions**
`"@stackframe/stack": "^2.6.12"`
`"next": "14.2.15"`

**Error**
```
StackAssertionError: Failed to send request to https://api.stack-auth.com/api/v1/users/me: 508 Infinite loop detected

INFINITE_LOOP_DETECTED


This is likely an error in Stack. Please make sure you are running the newest version and report it.
    at (node_modules/@stackframe/stack-shared/dist/interface/clientInterface.js:260:0)
    at (node_modules/@stackframe/stack-shared/dist/utils/results.js:122:0)
    at (node_modules/@stackframe/stack-shared/dist/interface/clientInterface.js:72:0)
    at (node_modules/@stackframe/stack-shared/dist/interface/clientInterface.js:135:0)
    at (node_modules/@stackframe/stack-shared/dist/interface/serverInterface.js:12:0)
    at (node_modules/@stackframe/stack-shared/dist/interface/serverInterface.js:22:25)
    at (node_modules/@stackframe/stack-shared/dist/interface/serverInterface.js:44:0)
    at (node_modules/@stackframe/stack/dist/esm/lib/stack-app.js:1264:0)
    at (node_modules/@stackframe/stack/dist/esm/lib/stack-app.js:120:0)
    at (node_modules/@stackframe/stack-shared/dist/utils/caches.js:43:0)
```

**Comment by hrmoller** [comment] 2024-10-23 20:18
Disabling the authcheck in `middleware.ts` does not prevent the error from happening.

**Comment by vermashobhit1994** [comment] 2024-10-28 21:43
I've used chatgpt tool and find out to add below code in below path
stack\packages\stack-shared\src\interface\clientInterface.ts 

here add below code 


    // Handle loop detection (508 status code) before processing other responses
    if (rawRes.status === 508) {
      return Result.error(new KnownErrors.LoopDetected(508, "Infinite loop detected in request chain"));
    }

before statement 

const processedRes = await this._processResponse(rawRes);

**Comment by fomalhautb** [comment] 2024-11-15 11:30
We have spent hours looking into this problem and still haven't figured out why. It seems like this only happened on Vercel starting recently and has no negative effect except for the error log. We will continue to investigate, but for now, you can probably just ignore this error.

**Comment by dimitrihartt** [comment] 2024-11-27 14:19
It happens right after toggling to true the option: Client-side Team Creation on the site projects dashbord team settings. Unfortunately we can't ignore it. Im using VERCEL too... PLEASE HELP!

**Comment by fomalhautb** [comment] 2024-12-06 04:37
I can't reproduce this anymore, it seems like Vercel has fixed it. Can someone confirm it?

**Comment by hrmoller** [comment] 2024-12-06 06:47
Actually I haven't seen it in the logs for a while but also haven't looked specifically. Will keep an eye out and let you know.

**Comment by fomalhautb** [comment] 2024-12-06 23:42
I will close this as it seems to be fixed. But if anyone sees this error again, feel free to reopen the issue.

**Closed by fomalhautb** 2024-12-06 23:42 UTC
